# --- 1. external HTTP ---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service
spec:
  type: ClusterIP
  selector:
    app: attendance-service
  ports:
    - name: http
      port: 80
      targetPort: 4054
---
# --- 2. in-cluster raw TCP ---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service-tcp
spec:
  clusterIP: None
  selector:
    app: attendance-service
  ports:
    - name: tcp-micro
      port: 5054
      targetPort: 5054
