apiVersion: v1
kind: Service
metadata:
  name: basic-data-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 4000
    - name: tcp
      port: 5000
      targetPort: 5000
  selector:
    app: basic-data-service
