# --- 1. external HTTP ---
apiVersion: v1
kind: Service
metadata:
  name: channel-service
spec:
  type: ClusterIP
  selector:
    app: channel-service
  ports:
    - name: http
      port: 80
      targetPort: 4013
---
# --- 2. in-cluster raw TCP ---
apiVersion: v1
kind: Service
metadata:
  name: channel-service-tcp
spec:
  clusterIP: None
  selector:
    app: channel-service
  ports:
    - name: tcp-micro
      port: 5013
      targetPort: 5013
