# --- 1. external HTTP ---
apiVersion: v1
kind: Service
metadata:
  name: device-service
spec:
  type: ClusterIP
  selector:
    app: device-service
  ports:
    - name: http
      port: 80
      targetPort: 4018
---
# --- 2. in-cluster raw TCP ---
apiVersion: v1
kind: Service
metadata:
  name: device-service-tcp
spec:
  clusterIP: None
  selector:
    app: device-service
  ports:
    - name: tcp-micro
      port: 5018
      targetPort: 5018
