apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
  labels:
    app: finance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-service
  template:
    metadata:
      labels:
        app: finance-service
    spec:
      containers:
        - name: finance-service
          image: saihu-acr-registry-vpc.cn-hongkong.cr.aliyuncs.com/prod/finance-service:latest
          ports:
            - containerPort: 4006
          envFrom:
            - secretRef:
                name: finance-service-secret
