apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-service
  labels:
    app: hr-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-service
  template:
    metadata:
      labels:
        app: hr-service
    spec:
      containers:
        - name: hr-service
          image: saihu-acr-registry-vpc.cn-hongkong.cr.aliyuncs.com/prod/hr-service:latest
          ports:
            - containerPort: 4003
          envFrom:
            - secretRef:
                name: hr-service-secret
