# --- 1. external HTTP ---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4012
  selector:
    app: inventory-service

# --- 2. in-cluster raw TCP ---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-tcp
spec:
  clusterIP: None
  selector:
    app: inventory-service
  ports:
    - name: tcp-micro
      port: 5012
      targetPort: 5012

