apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: saihu-acr-registry-vpc.cn-hongkong.cr.aliyuncs.com/prod/inventory-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4012
            - containerPort: 5012
          envFrom:
            - secretRef:
                name: inventory-service-secret
