apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 4008
    - name: tcp
      port: 5008
      targetPort: 5008
  selector:
    app: order-service
