apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: saihu-acr-registry-vpc.cn-hongkong.cr.aliyuncs.com/prod/payment-service:latest
          ports:
            - containerPort: 4007
          envFrom:
            - secretRef:
                name: payment-service-secret
