# --- 1. external HTTP ---
apiVersion: v1
kind: Service
metadata:
  name: payroll-service
spec:
  type: ClusterIP
  selector:
    app: payroll-service
  ports:
    - name: http
      port: 80
      targetPort: 4053
---
# --- 2. in-cluster raw TCP ---
apiVersion: v1
kind: Service
metadata:
  name: payroll-service-tcp
spec:
  clusterIP: None
  selector:
    app: payroll-service
  ports:
    - name: tcp-micro
      port: 5053
      targetPort: 5053
