# --- 1. external HTTP ---
apiVersion: v1
kind: Service
metadata:
  name: predict-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4024
  selector:
    app: predict-service

# --- 2. in-cluster raw TCP ---
apiVersion: v1
kind: Service
metadata:
  name: predict-service-tcp
spec:
  clusterIP: None
  selector:
    app: predict-service
  ports:
    - name: tcp-micro
      port: 5024
      targetPort: 5024
