apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-service
  labels:
    app: predict-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predict-service
  template:
    metadata:
      labels:
        app: predict-service
    spec:
      containers:
        - name: predict-service
          image: saihu-acr-registry-vpc.cn-hongkong.cr.aliyuncs.com/prod/predict-service:latest
          ports:
            - containerPort: 4004
          envFrom:
            - secretRef:
                name: predict-service-secret
