# --- 1. external HTTP /healthz ---
apiVersion: v1
kind: Service
metadata:
  name: workflow-service
spec:
  type: ClusterIP
  selector:
    app: workflow-service
  ports:
    - name: http
      port: 80
      targetPort: 4011
---
# --- 2. in-cluster raw TCP ---
apiVersion: v1
kind: Service
metadata:
  name: workflow-service-tcp
spec:
  clusterIP: None
  selector:
    app: workflow-service
  ports:
    - name: tcp-micro
      port: 5011
      targetPort: 5011
